# Generated by Django 4.1.4 on 2023-01-15 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('api_key', models.CharField(max_length=200)),
                ('check_type', models.CharField(choices=[('K', 'KITCHEN'), ('C', 'CLIENT')], max_length=32)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('K', 'KITCHEN'), ('C', 'CLIENT')], max_length=32)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('N', 'NEW'), ('R', 'RENDERED'), ('P', 'PRINTED')], default='N', max_length=32)),
                ('pdf_file', models.FileField(default=0, upload_to='')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer_app.printer')),
            ],
        ),
    ]
