version: '3'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6000:5432'
  redis:
    image: redis:6
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas:latest

volumes:
  data:
